CREATE ROLE dtlab_user WITH
    LOGIN
    SUPERUSER
    NOCREATEDB
    NOCREATEROLE
    INHERIT
    NOREPLICATION
    CONNECTION LIMIT -1
    PASSWORD '73X5VsJP6w';

CREATE DATABASE dtlab WITH
    OWNER = dtlab_user
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;

GRANT ALL PRIVILEGES ON DATABASE dtlab TO dtlab_user;

\q