"""Add public field to model and project

Revision ID: 04d620da0234
Revises: 6f5e833430a2
Create Date: 2023-10-10 14:21:17.763591

"""
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
import sqlalchemy_file

from alembic import op

# revision identifiers, used by Alembic.
revision = "04d620da0234"
down_revision = "6f5e833430a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("models", sa.Column("public", sa.Boolean(), nullable=False))
    op.add_column("projects", sa.Column("public", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "public")
    op.drop_column("models", "public")
    # ### end Alembic commands ###
