"""Add actual get_schema PGFunction

Revision ID: 26889f7b209c
Revises: cb0e2161d101
Create Date: 2023-08-14 02:45:26.053994

"""
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text

from alembic import op

# revision identifiers, used by Alembic.
revision = "26889f7b209c"
down_revision = "cb0e2161d101"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_get_schema = PGFunction(
        schema="public",
        signature="get_schema(datasource_id uuid)",
        definition="RETURNS json as\n    $$\n      SELECT schemas.json_schema\n      FROM schemas, datasources_json\n      WHERE schemas.id = datasources_json.schema_id AND datasources_json.id = datasource_id;\n    $$ language SQL",
    )
    op.replace_entity(public_get_schema)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_get_schema = PGFunction(
        schema="public",
        signature="get_schema(datasource_id uuid)",
        definition="returns json\n LANGUAGE sql\nAS $function$\n      SELECT json(name) from schemas\n    $function$",
    )
    op.replace_entity(public_get_schema)
    # ### end Alembic commands ###
