"""Add get_schema PGFunction

Revision ID: 5aa0f1e2b5ca
Revises: e829a27e94a2
Create Date: 2023-08-14 02:44:16.602109

"""
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text

from alembic import op

# revision identifiers, used by Alembic.
revision = "5aa0f1e2b5ca"
down_revision = "e829a27e94a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_get_schema = PGFunction(
        schema="public",
        signature="get_schema(datasource_id uuid)",
        definition="RETURNS json as\n    $$\n      SELECT json(name) from schemas\n    $$ language SQL",
    )
    op.create_entity(public_get_schema)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_get_schema = PGFunction(
        schema="public",
        signature="get_schema(datasource_id uuid)",
        definition="RETURNS json as\n    $$\n      SELECT json(name) from schemas\n    $$ language SQL",
    )
    op.drop_entity(public_get_schema)

    # ### end Alembic commands ###
