"""Add user_data field to user to store configuration for clients

Revision ID: a15e13355d37
Revises: 408170442304
Create Date: 2023-11-20 12:09:47.548986

"""
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
import sqlalchemy_file
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "a15e13355d37"
down_revision = "408170442304"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("user_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "user_data")
    # ### end Alembic commands ###
