"""Add DataSourceJSON tables

Revision ID: cb0e2161d101
Revises: 5aa0f1e2b5ca
Create Date: 2023-08-14 02:44:58.884202

"""
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "cb0e2161d101"
down_revision = "5aa0f1e2b5ca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "datasources_json",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("schema_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["datasources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["schema_id"],
            ["schemas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "datapoints_json",
        sa.Column("datetime", sa.DateTime(), nullable=False),
        sa.Column("datasource_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint("jsonb_matches_schema(get_schema(datasource_id), payload)", name="check_json_valid"),
        sa.ForeignKeyConstraint(["datasource_id"], ["datasources_json.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("datetime", "datasource_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("datapoints_json")
    op.drop_table("datasources_json")
    # ### end Alembic commands ###
